#!/bin/bash
#
## Monitor Resolution
xrandr --output HDMI-1 --mode 1920x1080 --rate 100

# BSPWM Configuration
_bc() {
  bspc config "$@"
}

# Set up displays
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# BSPWM Configuration
_bc window_gap                       2
_bc top_padding                      26
_bc top_monocle_padding              0
_bc border_width                     2
_bc bottom_padding                   0
_bc left_padding                     0
_bc right_padding                    0
_bc single_monocle                   false
_bc click_to_focus                   false
_bc split_ratio                      0.50
_bc borderless_monocle               true
_bc gapless_monocle                  true
_bc focus_by_distance                true
_bc paddingless_monocle              true
_bc focus_follows_pointer            true
_bc ignore_ewmh_focus                true
_bc history_aware_focus              true
_bc remove_disabled_monitors         true
_bc pointer_modifier mod4 
_bc pointer_action1 move
_bc pointer_action2 resize_side
_bc pointer_action3 resize_corner

# Colors
background="#2e3440"
foreground="#d8dee9"
accent="#00F7FF"
active="#bf616a"
focused="#00F7FF"
normal="#4c566a"
_bc normal_border_color "$normal"
_bc focused_border_color "$focused"
_bc active_border_color "$active"

# Rules
bspc rule -a mpv state=tiled
bspc rule -a flameshot state='floating'
bspc rule -a *:SPLASH state=floating
bspc desktop -f 1
bspc rule -a qBittorrent desktop='^5' follow=off focus=off
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on


# Init-Daemons
command -v sxhkd && sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" 
command -v polybar && pkill polybar && polybar &
command -v dunst && dunst &
command -v qbittorrent && qbittorrent &
command -v easyeffects && easyeffects &
command -v feh && feh --bg-scale ~/Pictures/wallpapers/178343.jpg &
